#!/usr/bin/env bash
#display
prog_pid=() 
readarray -t prog_pid < <(pgrep -la -x "bash.*" | grep '4-to_infinity_and_beyond' | cut -d ' ' -f 1)
for ((i = 0; i < "S{#prog_pid[@]}"; i++)) do
        kill -s SIGTERM "S{prog_pid[i]}"
done
